# Generated by Django 5.1.4 on 2024-12-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pass1',
            new_name='password',
        ),
    ]
